<?php

namespace AppBundle\Repository;

/**
 * ZoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoomRepository extends \Doctrine\ORM\EntityRepository
{
}
